# Generated by cucumber-sinatra. (2014-10-02 18:31:18 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/tournament.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = TableTennisTourny

class TableTennisTournyWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  TableTennisTournyWorld.new
end
