# Generated by cucumber-sinatra. (2014-10-02 18:31:18 +0100)

ENV['RACK_ENV'] = 'test'

# require File.join(File.dirname(__FILE__), '..', '..', 'lib/tournament.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = table_tennis_tourny

class table_tennis_tournyWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  table_tennis_tournyWorld.new
end
